controller_manager:
  ros__parameters:
    update_rate: 50
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    # forward_track_controller:
    #   type: position_controllers/JointGroupPositionController
    # backward_track_controller:
    #   type: position_controllers/JointGroupPositionController

    # forward_wheel_controller:
    #   type: velocity_controllers/JointGroupVelocityController
    # backward_wheel_controller:
    #   type: velocity_controllers/JointGroupVelocityController


diff_cont:
  ros__parameters:
    # type: skid_steer_drive_controller/SkidSteerDriveController

    left_wheel_names: ['left_wheel1_joint','left_wheel2_joint','left_wheel3_joint']
    right_wheel_names: ['right_wheel1_joint','right_wheel2_joint','right_wheel3_joint']

    wheel_separation: 0.23
    wheels_per_side: 1
    # num_wheel_pairs: 3
    wheel_radius: 0.06
    
    publish_rate: 100.0

    base_frame_id: base_link
    enable_odom_tf: true
    odom_frame_id: odom

    # open_loop: true

    # wheel_separation_multiplier: 1.0    для доп колёс, так как они дальше друг от друга
    # left_wheel_radius_multiplier: 1.0   для доп колёс, так как они меньшего радиуса



    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    use_stamped_vel: false

# forward_track_controller:
#   ros__parameters:
#     joints: ['forward_track_joint']
#     pid:
#       p: 100.0
#       i: 0.0
#       d: 10.0

# backward_track_controller:
#   ros__parameters:
#     joints: ['backward_track_joint']
#     pid:
#       p: 100.0
#       i: 0.0
#       d: 10.0

# forward_wheel_controller:
#   ros__parameters:
#     joints: ['forward_wheel_joint']  
#     command_interfaces: ['velocity']
#     state_interfaces: ['position','velocity']
#     pid:
#       p: 0.1    
#       i: 0.01
#       d: 0.0

# backward_wheel_controller:
#   ros__parameters:
#     joints: ['backward_wheel_joint']  
#     command_interfaces: ['velocity']
#     state_interfaces: ['position','velocity']
#     pid:
#       p: 0.1    
#       i: 0.01
#       d: 0.0