twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.1
        priority: 10
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.1
        priority: 20
